### ISSUE TITLE
kubernetes v1.12.3+: [kubelet-check] Initial timeout of 40s passed.

### ISSUE THREAD

**Issue by medyagh** [kubernetes/kubelet#23] opened 2021-02-21 00:09 UTC
Hello, on minikube we updated our default kubernetes to v1.20.4 and we noticed bumping from v1.20.2 to v1.20.3 causes 1 minute slow down on miikube which the logs shows it is spending that time in [kubelet-check] Initial timeout of 40s passed.

```

    ▪ Booting up control plane ...I0220 15:44:24.522119   82905 command_runner.go:123] > [control-plane] Creating static Pod manifest for "kube-apiserver"
I0220 15:44:24.522344   82905 command_runner.go:123] > [control-plane] Creating static Pod manifest for "kube-controller-manager"
I0220 15:44:24.522442   82905 command_runner.go:123] > [control-plane] Creating static Pod manifest for "kube-scheduler"
I0220 15:44:24.522659   82905 command_runner.go:123] > [etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
I0220 15:44:24.522894   82905 command_runner.go:123] > [wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
| I0220 15:45:04.513403   82905 command_runner.go:123] > [kubelet-check] Initial timeout of 40s passed.
/ I0220 15:45:28.017602   82905 command_runner.go:123] > [apiclient] All control plane components are healthy after 63.506128 seconds
I0220 15:45:28.017909   82905 command_runner.go:123] > [upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
I0220 15:45:28.031480   82905 command_runner.go:123] > [kubelet] Creating a ConfigMap "kubelet-config-1.20" in namespace kube-system with the configuration for the kubelets in the cluster
- I0220 15:45:28.557112   82905 command_runner.go:123] > [upload-certs] Skipping phase. Please see --upload-certs
I0220 15:45:28.557337   82905 command_runner.go:123] > [mark-control-plane] Marking the node minikube as control-plane by adding the labels "node-role.kubernetes.io/master=''" and "node-role.kubernetes.io/control-plane='' (deprecated)"
| I0220 15:45:29.070246   82905 command_runner.go:123] > [bootstrap-token] Using token: ckmqq4.dov5m97q5ko44fpg
I0220 15:45:29.159638   82905 out.go:140]     ▪ Configuring RBAC rules ..
```

I am curious if you are aware of any change that is happened since kubernetes v1.20.3 that has caused this ?
v1.20.2 does NOT have this problem, more details https://github.com/kubernetes/minikube/issues/10545

**Comment by BenTheElder** [comment] 2021-02-21 03:40
ref: https://github.com/kubernetes/kubeadm/issues/2395#issuecomment-782784169 for the likely root cause @neolit123 
note: 1.20.4 is 1.20.3 + a small test revert related to conformance.

**Comment by neolit123** [comment] 2021-04-27 13:37
update

PR in master (1.22) merged:
https://github.com/kubernetes/kubernetes/pull/99336

the change is backported all the way back to 1.18 (inc); backport PRs are pending.
https://github.com/kubernetes/kubernetes/pull/99336#issuecomment-824441152

/close

**Closed** 2021-04-27 13:37 UTC
